export type Categoria = 'alitas' | 'carnes' | 'tajadas' | 'pupusas' | 'bebidas' | 'promos';
export type Subcategoria = 'refrescos' | 'cervezas';

export interface ItemMenu {
  id: string;
  categoria: Categoria;
  subcategoria?: Subcategoria;
  nombre: string;
  descripcion: string;
  precio: number;
  acompanamientos?: string[];
  dia?: string;
  spice?: 'mild' | 'medium' | 'hot';
  destacado?: boolean;
  valorTag?: string;
  precioRegular?: number;
  emoji: string;
  gradientFrom?: string;
  gradientTo?: string;
  image_url?: string | null;
}

export const MENU_ITEMS: ItemMenu[] = [
  // ── Alitas ─────────────────────────────────────────────────────────
  {
    id: 'alitas-6',
    categoria: 'alitas',
    nombre: '6 Alitas',
    descripcion: 'Piel crocante, carne que se cae del hueso. BB o Búfalo a elegir.',
    precio: 180,
    acompanamientos: ['Papas fritas', 'Salsa', 'Aderezo'],
    spice: 'medium',
    destacado: true,
    emoji: '🍗',
    gradientFrom: '#2A1400',
    gradientTo: '#E85D04',
  },
  {
    id: 'alitas-12',
    categoria: 'alitas',
    nombre: '12 Alitas',
    descripcion: 'La orden para compartir. BB o Búfalo — elige tu veneno.',
    precio: 320,
    acompanamientos: ['Papas fritas', 'Salsa', 'Aderezo'],
    spice: 'medium',
    destacado: true,
    emoji: '🍗',
    gradientFrom: '#1A0A00',
    gradientTo: '#C1121F',
  },
  // ── Carnes ─────────────────────────────────────────────────────────
  {
    id: 'carne-asada-cerdo',
    categoria: 'carnes',
    nombre: 'Carne Asada de Cerdo',
    descripcion: 'Carne de cerdo asada a las brasas, jugosa por dentro y dorada por fuera.',
    precio: 160,
    acompanamientos: ['Tajadas', 'Frijoles fritos', 'Encurtido', 'Aderezos'],
    emoji: '🥩',
    gradientFrom: '#1A0800',
    gradientTo: '#8B3A0F',
  },
  {
    id: 'chuleta-asada-cerdo',
    categoria: 'carnes',
    nombre: 'Chuleta Asada de Cerdo',
    descripcion: 'Chuleta de cerdo asada a punto perfecto con todos los acompañamientos.',
    precio: 160,
    acompanamientos: ['Tajadas', 'Frijoles fritos', 'Encurtido', 'Aderezos'],
    emoji: '🍖',
    gradientFrom: '#200A00',
    gradientTo: '#7A2B00',
  },
  {
    id: 'chuleta-chorizo',
    categoria: 'carnes',
    nombre: 'Chuleta con Chorizo',
    descripcion: 'Chuleta asada acompañada de chorizo artesanal a la parrilla.',
    precio: 160,
    acompanamientos: ['Tajadas', 'Frijoles molidos', 'Encurtido', 'Aderezos'],
    emoji: '🍖',
    gradientFrom: '#200A00',
    gradientTo: '#7A2B00',
  },
  {
    id: 'carne-cerdo-chorizo',
    categoria: 'carnes',
    nombre: 'Carne de Cerdo con Chorizo',
    descripcion: 'Carne asada de cerdo con chorizo a la parrilla. El combo clásico de la casa.',
    precio: 160,
    acompanamientos: ['Tajadas', 'Frijoles molidos', 'Encurtido', 'Aderezos'],
    emoji: '🥩',
    gradientFrom: '#1A0800',
    gradientTo: '#8B3A0F',
  },
  // ── Tajadas ─────────────────────────────────────────────────────────
  {
    id: 'tajadas-preparadas',
    categoria: 'tajadas',
    nombre: '1 Orden de Tajadas',
    descripcion: 'Tajadas fritas preparadas con todos los extras de la casa.',
    precio: 90,
    acompanamientos: ['Carne molida', 'Ensalada', 'Encurtido', 'Aderezo'],
    emoji: '🍌',
    gradientFrom: '#1A1400',
    gradientTo: '#856404',
  },
  {
    id: 'tajadas-doble',
    categoria: 'tajadas',
    nombre: '2 Órdenes de Tajadas',
    descripcion: 'Doble porción de tajadas preparadas. Ideal para compartir.',
    precio: 170,
    acompanamientos: ['Carne molida', 'Encurtido', 'Aderezo'],
    valorTag: 'AHORRÁS L.10',
    precioRegular: 180,
    emoji: '🍌',
    gradientFrom: '#1A1400',
    gradientTo: '#856404',
  },
  // ── Pupusas ─────────────────────────────────────────────────────────
  {
    id: 'pupusas-quesillo',
    categoria: 'pupusas',
    nombre: '3 Pupusas de Quesillo',
    descripcion: 'Rellenas de quesillo derretido. Incluye 1 galleta dulce gratis.',
    precio: 100,
    acompanamientos: ['Salsa', 'Ensalada', 'Encurtido'],
    dia: 'Mié / Jue',
    valorTag: '🍪 GALLETA GRATIS',
    emoji: '🫓',
    gradientFrom: '#1A1200',
    gradientTo: '#6B4C00',
  },
  {
    id: 'pupusas-chicharron',
    categoria: 'pupusas',
    nombre: '3 Pupusas de Chicharrón',
    descripcion: 'Rellenas de chicharrón crujiente. Incluye 1 galleta dulce gratis.',
    precio: 110,
    acompanamientos: ['Salsa', 'Ensalada', 'Encurtido'],
    dia: 'Mié / Jue',
    valorTag: '🍪 GALLETA GRATIS',
    emoji: '🫓',
    gradientFrom: '#200E00',
    gradientTo: '#7A3800',
  },
  // ── Bebidas — Refrescos ─────────────────────────────────────────────
  {
    id: 'beb-portatil',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Portátil',
    descripcion: 'Coca Cola, Pepsi, Mirinda y más sabores.',
    precio: 30,
    emoji: '🥤',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-mtn-dew-grande',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Mountain Dew Grande / AMP Grande',
    descripcion: 'Mountain Dew o AMP en presentación grande.',
    precio: 30,
    emoji: '🥤',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-adrenaline-grande',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Adrenaline Grande',
    descripcion: 'Bebida energizante en presentación grande.',
    precio: 50,
    emoji: '⚡',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-adrenaline-chica',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Adrenaline Pequeña',
    descripcion: 'Bebida energizante en presentación pequeña.',
    precio: 45,
    emoji: '⚡',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-gatorade',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Gatorade',
    descripcion: 'Bebida hidratante en distintos sabores.',
    precio: 40,
    emoji: '🥤',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-fury',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Fury',
    descripcion: 'Jugo de fruta en varios sabores.',
    precio: 30,
    emoji: '🥤',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-lipton',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Té Lipton Botella',
    descripcion: 'Té helado Lipton en botella.',
    precio: 28,
    emoji: '🍵',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-lata-pepsi',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Lata Pepsi / Mountain Dew',
    descripcion: 'Pepsi, Mountain Dew y otros sabores en lata.',
    precio: 25,
    emoji: '🥤',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-aguazul',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Botella Aguazul',
    descripcion: 'Agua purificada Aguazul.',
    precio: 25,
    emoji: '💧',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-lata-jugo',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Lata Jugo',
    descripcion: 'Jugo en lata, varios sabores.',
    precio: 15,
    emoji: '🧃',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-agua',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'Botella Agua',
    descripcion: 'Agua purificada en botella pequeña.',
    precio: 13,
    emoji: '💧',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'beb-amp-chica',
    categoria: 'bebidas',
    subcategoria: 'refrescos',
    nombre: 'AMP Botella Pequeña',
    descripcion: 'Bebida energizante AMP en presentación pequeña.',
    precio: 22,
    emoji: '⚡',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  // ── Bebidas — Cervezas ──────────────────────────────────────────────
  {
    id: 'cerv-corona',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Corona',
    descripcion: 'Cerveza Corona, refrescante y ligera.',
    precio: 55,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'cerv-ultra-botella',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Cerveza Ultra Botella',
    descripcion: 'Ultra en botella.',
    precio: 50,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'cerv-coors',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Coors Light / Miller Draft / Ultra Lata',
    descripcion: 'Coors Light, Miller Draft o Ultra en lata.',
    precio: 45,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'cerv-salva-vida-ml',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Salva Vida Lata ML',
    descripcion: 'Salva Vida en lata mediana.',
    precio: 40,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'cerv-bud-light',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Bud Light',
    descripcion: 'Bud Light, la clásica ligera.',
    precio: 35,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  {
    id: 'cerv-barena',
    categoria: 'bebidas',
    subcategoria: 'cervezas',
    nombre: 'Barena / Salva Vida / Imperial Lata',
    descripcion: 'Barena, Salva Vida Normal o Imperial en lata.',
    precio: 30,
    emoji: '🍺',
    gradientFrom: '#001A12',
    gradientTo: '#00572E',
  },
  // ── Promos ──────────────────────────────────────────────────────────
  {
    id: 'promo-viernes-carne-asada',
    categoria: 'promos',
    nombre: '2 Platos: Carne Asada de Cerdo',
    descripcion: 'Dos platos de carne asada de cerdo. Solo los viernes.',
    precio: 300,
    acompanamientos: ['Tajadas', 'Frijoles fritos', 'Encurtido', 'Aderezos'],
    dia: 'Viernes',
    valorTag: 'AHORRÁS L.20',
    precioRegular: 320,
    emoji: '🎉',
    gradientFrom: '#1A0400',
    gradientTo: '#8B0000',
  },
  {
    id: 'promo-viernes-chuleta-asada',
    categoria: 'promos',
    nombre: '2 Platos: Chuleta Asada de Cerdo',
    descripcion: 'Dos chuletas asadas de cerdo. Solo los viernes.',
    precio: 300,
    acompanamientos: ['Tajadas', 'Frijoles fritos', 'Encurtido', 'Aderezos'],
    dia: 'Viernes',
    valorTag: 'AHORRÁS L.20',
    precioRegular: 320,
    emoji: '🎉',
    gradientFrom: '#1A0600',
    gradientTo: '#7A1F00',
  },
  {
    id: 'promo-alitas-14',
    categoria: 'promos',
    nombre: '14 Alitas BB o Búfalo',
    descripcion: 'La promo para compartir. Incluye 1 galleta dulce gratis.',
    precio: 300,
    acompanamientos: ['Papas fritas', 'Kétchup', 'Aderezo de la casa'],
    dia: 'Mié / Jue / Dom',
    spice: 'medium',
    destacado: true,
    valorTag: '2 ALITAS EXTRA',
    emoji: '🔥',
    gradientFrom: '#200800',
    gradientTo: '#C1121F',
  },
  {
    id: 'promo-alitas-7',
    categoria: 'promos',
    nombre: '7 Alitas BB o Búfalo',
    descripcion: 'Promo personal con galleta dulce gratis.',
    precio: 180,
    acompanamientos: ['Papas fritas', 'Kétchup', 'Aderezo de la casa'],
    dia: 'Mié / Jue / Dom',
    spice: 'medium',
    valorTag: '1 ALITA GRATIS',
    emoji: '🔥',
    gradientFrom: '#1A0600',
    gradientTo: '#E85D04',
  },
];

export const CATEGORIAS: { id: Categoria | 'todos'; label: string }[] = [
  { id: 'promos',  label: 'Promos'   },
  { id: 'alitas',  label: 'Alitas'   },
  { id: 'carnes',  label: 'Carnes'   },
  { id: 'tajadas', label: 'Tajadas'  },
  { id: 'pupusas', label: 'Pupusas'  },
  { id: 'bebidas', label: 'Bebidas'  },
  { id: 'todos',   label: 'Ver todo' },
];
